# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.1
#   kernelspec:
#     display_name: .venv
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Deep Learning Model Selection and Training
#
# In this notebook, we will focus exclusively on Phase 1 testing and selection for Deep Learning:
# - Validate heavy Deep Learning Baselines (Inception V3, VGG16, DenseNet201).
# - Perform a grid search across Transfer Learning Initialization Strategies for MobileViT.
# - Execute runs using the unified Lightning `train_dl.py` scripts and `run_grid_search.py`.

# %%
# %load_ext autoreload
# %autoreload 2
# %matplotlib inline

import sys
from pathlib import Path

project_root = Path("../../").resolve()
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

# %%
from jute_disease.utils.constants import DEFAULT_SEED
from jute_disease.utils.logger import get_logger
from jute_disease.utils.seed import seed_everything

# %%
logger = get_logger(__name__)
seed_everything(DEFAULT_SEED)

# %% [markdown]
# ## 1. Heavy DL Baselines
# Training InceptionV3, VGG16, and DenseNet201 to establish standard benchmarks using pure ImageNet pretraining.
#
# *Note: We will invoke `scripts/train_dl.py` via Python subprocess or bash commands (`!uv run python scripts/train_dl.py`)*

# %%

# %% [markdown]
# ## 2. MobileViT Transfer Learning Grid
# Evaluating MobileViT initialization strategies to test the impact of domain-adaptive pretraining:
# 1. **Level 1**: ImageNet -> Jute
# 2. **Level 2**: ImageNet -> PlantVillage -> Jute
# 3. **Level 3**: ImageNet -> PlantVillage -> PlantDoc -> Jute
#
# *Note: We will use `scripts/run_grid_search.py` leveraging `configs/grid/mobilevit_grid.yaml`*

# %%

# %% [markdown]
# ## 3. WandB Analysis
# Reviewing the logs generated by Weights & Biases to identify the "Champion" baseline and the most effective transfer learning initialization strategy.

# %%
