learning_rate:
  - 0.01
  - 0.005
  - 0.001  # Baseline
  - 0.0005
  - 0.0001

locked_params:
  name: "level_1_imagenet"
  weights_path: "imagenet"
  dropout_rate: 0.1

fixed_params:
  input_resolution: [256, 256]
  batch_size: 32
  optimizer: "AdamW"
  reduce_lr_factor: 0.1
  reduce_lr_patience: 3
  max_epochs: 50
  early_stopping_patience: 20
  weight_decay: 0.05
  loss_function: "CrossEntropyLoss"
  num_folds: 1
  num_classes: 6
  random_seed: 42
